# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c739fb6667fac6af61e445491e3edd63d05b8b09ba04482ea618a9014ea8738ec7a041b68a996245d896dbd02fec88005d819c868c00ef11b70504854b0f8f5

test:
  secret_key_base: 87ce60677792ad83849200550651060d8f6db7a66a148e16ef3fffca15d5e10d38e970730324c76066198947acc60631f963baab124db1da21ea1caee5d42afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
